In [1]:
import duckdb as ddb
import pandas as pd

In [2]:
sql_query = '''
show tables; 
'''

with ddb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                              name
0   bronze_parking_violation_codes
1        bronze_parking_violations
2                      first_model
3              gold_ticket_metrics
4             gold_vehicle_metrics
5          parking_violation_codes
6          parking_violations_2025
7                        ref_model
8   silver_parking_violation_codes
9        silver_parking_violations
10        silver_violation_tickets
11       silver_violation_vehicles

In [3]:
sql_query_import_1 = """
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT * 
FROM read_csv_auto(
    'data/DOF_Parking_Violation_Codes_20260603.csv',
    normalize_names=True
)
"""

In [4]:
sql_query_import_2 = """
CREATE OR REPLACE TABLE parking_violations_2025 AS
SELECT * 
FROM read_csv_auto(
    'data/sample_parking_violations_2025.csv',
    normalize_names=True
)
"""

In [5]:
with ddb.connect("data/nyc_parking_violations.db") as con:
    con.sql(sql_query_import_1)
    con.sql(sql_query_import_2)

In [6]:
sql_query = """
SELECT * FROM parking_violation_codes
LIMIT 5;
"""

with ddb.connect("data/nyc_parking_violations.db") as con:
    display(con.sql(sql_query).df())

,code,definition,manhattan_96th_st_below,all_other_areas
0,1,FAILURE TO DISPLAY BUS PERMIT,515,515
1,2,NO OPERATOR NAM/ADD/PH DISPLAY,515,515
2,3,UNAUTHORIZED PASSENGER PICK-UP,515,515
3,4,BUS PARKING IN LOWER MANHATTAN,115,115
4,5,BUS LANE VIOLATION,250,250

In [7]:
sql_query = """
show tables; 
"""

with ddb.connect("data/nyc_parking_violations.db") as con:
    display(con.sql(sql_query).df())

                              name
0   bronze_parking_violation_codes
1        bronze_parking_violations
2                      first_model
3              gold_ticket_metrics
4             gold_vehicle_metrics
5          parking_violation_codes
6          parking_violations_2025
7                        ref_model
8   silver_parking_violation_codes
9        silver_parking_violations
10        silver_violation_tickets
11       silver_violation_vehicles

In [8]:
sql_query = """
SELECT * FROM ref_model;
"""

with ddb.connect("data/nyc_parking_violations.db") as con:
    display(con.sql(sql_query).df())

   count_star()
0            97

In [9]:
sql_query = """
SELECT * FROM bronze_parking_violation_codes
LIMIT 3;
"""

with ddb.connect("data/nyc_parking_violations.db") as con:
    display(con.sql(sql_query).df())

,violation_code,definition,manhattan_96th_st_below,all_other_areas
0,1,FAILURE TO DISPLAY BUS PERMIT,515,515
1,2,NO OPERATOR NAM/ADD/PH DISPLAY,515,515
2,3,UNAUTHORIZED PASSENGER PICK-UP,515,515

In [10]:
sql_query = """
SELECT * FROM bronze_parking_violations
LIMIT 3;
"""

with ddb.connect("data/nyc_parking_violations.db") as con:
    display(con.sql(sql_query).df())

,summons_number,registration_state,plate_type,issue_date,violation_code,vehicle_body_type,vehicle_make,issuing_agency,vehicle_expiration_date,violation_location,violation_precinct,issuer_precinct,issuer_code,issuer_command,issuer_squad,violation_time,violation_county,violation_legal_code,vehicle_color,vehicle_year
0,4906674367,TX,PAS,2024-07-08,36.0,4D,DODGE,V,0.0,NaN,0.0,0.0,0.0,None,None,0416A,QN,True,NaN,2013.0
1,4906075502,NY,PAS,2024-07-09,36.0,4DSD,CHEVR,V,0.0,NaN,0.0,0.0,0.0,None,None,0424P,BX,True,GY,2018.0
2,4907839261,NJ,PAS,2024-07-17,36.0,UT,AUDI,V,0.0,NaN,0.0,0.0,0.0,None,None,0625P,BX,True,NaN,2022.0

In [11]:
sql_query = """
SELECT * FROM silver_violation_tickets
LIMIT 3; 
"""

with ddb.connect("data/nyc_parking_violations.db") as con:
    display(con.sql(sql_query).df())

,summons_number,issue_date,violation_code,is_manhattan_96th_st_below,issuing_agency,violation_location,issuer_precinct,issuer_code,issuer_command,issuer_squad,violation_time,violation_county,violation_legal_code,fee_usd
0,4906674367,2024-07-08,36.0,False,V,NaN,0.0,0.0,None,None,0416A,QN,True,NaN
1,4906075502,2024-07-09,36.0,False,V,NaN,0.0,0.0,None,None,0424P,BX,True,NaN
2,4907839261,2024-07-17,36.0,False,V,NaN,0.0,0.0,None,None,0625P,BX,True,NaN

In [14]:
sql_query = """
SELECT * FROM gold_ticket_metrics 
"""

with ddb.connect("data/nyc_parking_violations.db") as con:
    display(con.sql(sql_query).df())

    violation_code  ticket_count  total_revenue_usd
0              5.0           424            31750.0
1             36.0          3992            14400.0
2             12.0           135             7000.0
3              7.0           477              950.0
4             40.0           323                NaN
5             38.0           680                NaN
6             46.0           162                NaN
7             71.0           284                NaN
8             51.0            27                NaN
9             98.0            41                NaN
10            74.0           134                NaN
11            48.0            31                NaN
12            14.0           420                NaN
13            47.0            31                NaN
14            83.0             4                NaN
15            42.0            14                NaN
16             6.0             1                NaN
17            77.0             1                NaN
18            10.0            35                NaN
19            62.0             1                NaN
20            75.0             8                NaN
21            13.0             6                NaN
22            87.0            11                NaN
23            25.0             1                NaN
24            21.0          1198                NaN
25            37.0           142                NaN
26            16.0           130                NaN
27            84.0            42                NaN
28            22.0             5                NaN
29            68.0            12                NaN
30            82.0             5                NaN
31            20.0           317                NaN
32            72.0            12                NaN
33            11.0             3                NaN
34            23.0             1                NaN
35             0.0             1                NaN
36            60.0             1                NaN
37            66.0            21                NaN
38            78.0            23                NaN
39            80.0             3                NaN
40            41.0             2                NaN
41            63.0             3                NaN
42            45.0             2                NaN
43            17.0            49                NaN
44            31.0           154                NaN
45            53.0            24                NaN
46            76.0            27                NaN
47            50.0            48                NaN
48            19.0           133                NaN
49            69.0           149                NaN
50            70.0           209                NaN
51            99.0             4                NaN
52            64.0             5                NaN
53            33.0             3                NaN
54            18.0            16                NaN
55            73.0             5                NaN
56            61.0             4                NaN
57            85.0             2                NaN
58            67.0             1                NaN
59             9.0             1                NaN

In [15]:
sql_query = """
SELECT * FROM gold_vehicle_metrics
"""

with ddb.connect("data/nyc_parking_violations.db") as con:
    display(con.sql(sql_query).df())

   registration_state  ticket_count
0                  NJ          1042
1                  PA           400
2                  FL           225
3                  CT           185
4                  VA            98
5                  GA            95
6                  MA            71
7                  MD            65
8                  IN            59
9                  IL            56
10                 NC            54
11                 TX            53
12                 OH            34
13                 CA            33
14                 SC            29
15                 ME            25
16                 AZ            23
17                 99            19
18                 TN            19
19                 MN            15
20                 RI            13
21                 AL            13
22                 MI            12
23                 DE            11
24                 VT            10
25                 WA             9
26                 NH             8
27                 WI             7
28                 MT             7
29                 MO             6
30                 OR             5
31                 SD             5
32                 OK             5
33                 CO             5
34                 MS             5
35                 KS             4
36                 ON             4
37                 DC             4
38                 NM             3
39                 WV             3
40                 AR             3
41                 KY             3
42                 UT             3
43                 NV             2
44                 LA             2
45                 ID             1
46                 PR             1
47                 QB             1